export const seededJobs = [
  {
    job_id: "google_1",
    job_apply_link: "https://careers.google.com/jobs/results/",
    job_title: "Software Engineer, Core Systems",
    employer_name: "Google",
    employer_logo: "https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg",
    job_employment_type: "Full-time",
    job_posted_at_datetime_utc: new Date().toISOString(),
    job_city: "Mountain View",
    job_state: "CA",
    job_country: "USA",
    job_is_remote: false,
    job_description: "Google is proud to be an equal opportunity workplace and is an affirmative action employer. We are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity or Veteran status. Join our Core Systems team to build the infrastructure that powers Google's services."
  },
  {
    job_id: "amazon_1",
    job_apply_link: "https://amazon.jobs/en/",
    job_title: "Senior Full Stack Engineer",
    employer_name: "Amazon",
    employer_logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    job_employment_type: "Full-time",
    job_posted_at_datetime_utc: new Date(Date.now() - 86400000).toISOString(),
    job_city: "Seattle",
    job_state: "WA",
    job_country: "USA",
    job_is_remote: true,
    job_description: "Amazon is looking for a passionate, results-oriented, inventive Senior Full Stack Engineer. You will have the opportunity to build high-performance systems and drive the technical direction of our customer-facing applications."
  },
  {
    job_id: "microsoft_1",
    job_apply_link: "https://jobs.careers.microsoft.com/global/en/search",
    job_title: "Cloud Solutions Architect",
    employer_name: "Microsoft",
    employer_logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    job_employment_type: "Full-time",
    job_posted_at_datetime_utc: new Date(Date.now() - 172800000).toISOString(),
    job_city: "Redmond",
    job_state: "WA",
    job_country: "USA",
    job_is_remote: false,
    job_description: "Microsoft Azure is a growing collection of integrated cloud services that developers and IT professionals use to build, deploy, and manage applications through our global network of datacenters. We are seeking a Cloud Solutions Architect to help our top enterprise customers build scalable solutions."
  },
  {
    job_id: "flipkart_1",
    job_apply_link: "https://www.flipkartcareers.com/",
    job_title: "Frontend Developer (React)",
    employer_name: "Flipkart",
    employer_logo: "https://upload.wikimedia.org/wikipedia/en/7/7a/Flipkart_logo.svg",
    job_employment_type: "Full-time",
    job_posted_at_datetime_utc: new Date(Date.now() - 43200000).toISOString(),
    job_city: "Bengaluru",
    job_state: "Karnataka",
    job_country: "India",
    job_is_remote: false,
    job_description: "As a Frontend Developer at Flipkart, you will be responsible for implementing visual elements that users see and interact with in a web application. You will work closely with the design team and backend engineers to build a world-class e-commerce experience."
  },
  {
    job_id: "tata_1",
    job_apply_link: "https://www.tcs.com/careers",
    job_title: "Systems Engineer",
    employer_name: "Tata Consultancy Services (TCS)",
    employer_logo: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg",
    job_employment_type: "Full-time",
    job_posted_at_datetime_utc: new Date(Date.now() - 259200000).toISOString(),
    job_city: "Mumbai",
    job_state: "Maharashtra",
    job_country: "India",
    job_is_remote: true,
    job_description: "TCS is an IT services, consulting and business solutions organization that has been partnering with many of the world's largest businesses in their transformation journeys for over 50 years. We are hiring Systems Engineers to develop enterprise solutions."
  },
  {
    job_id: "wipro_1",
    job_apply_link: "https://careers.wipro.com/",
    job_title: "Data Scientist",
    employer_name: "Wipro",
    employer_logo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg",
    job_employment_type: "Full-time",
    job_posted_at_datetime_utc: new Date(Date.now() - 345600000).toISOString(),
    job_city: "Pune",
    job_state: "Maharashtra",
    job_country: "India",
    job_is_remote: false,
    job_description: "Wipro Limited is a leading global information technology, consulting and business process services company. We are looking for Data Scientists to analyze large datasets and develop machine learning models to solve complex business problems."
  },
  {
    job_id: "zoho_1",
    job_apply_link: "https://careers.zohocorp.com/",
    job_title: "Product Marketing Manager",
    employer_name: "Zoho",
    employer_logo: "https://upload.wikimedia.org/wikipedia/commons/4/41/Zoho_Corporation_logo.png",
    job_employment_type: "Full-time",
    job_posted_at_datetime_utc: new Date(Date.now() - 86400000).toISOString(),
    job_city: "Chennai",
    job_state: "Tamil Nadu",
    job_country: "India",
    job_is_remote: false,
    job_description: "Zoho offers a comprehensive suite of award-winning online business, productivity & collaboration applications. We are looking for a Product Marketing Manager to craft compelling narratives and drive go-to-market strategies for our new SaaS products."
  }
];
